[LM-9392] Data Wrapper Model and UUID changes
NateshR/LikeMinds-ReactNative-Chat-SX pull request #154
Opened 2023-08-15 19:28 UTC by arnavr15

## Description

**Features**
- Did model changes according to data wrapper class
- Did UUID changed

**Bugs**

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Hotfix (fixes a breaking changes)
- [x] New Feature (non-breaking change which adds functionality)
- [ ] Other, please describe:

### Author Checklist

- [x] Assignee added
- [x] Reviewer added
- [x] Description added
- [ ] Unit test cases added

### Reviewer Checklist

- [ ] PR title starts with Jira ticket number prefix
- [ ] If hotfix, Add Hotfix as prefix in PR title
- [ ] Label added
- [ ] Commit messages follows standard format (added, changed, removed, code commented and chore)
- [ ] Description about the Feature/ Bugs added

2023-08-16 13:04 UTC, jaixchaudhary commented on ChatSX/store/reducers/fileUploadReducer.ts
> +      // ??
type the use case of the function

2023-08-16 13:05 UTC, jaixchaudhary commented on index.js
> +export const myClient = LMChatClient.setApiKey(
remove api key

2023-08-16 13:05 UTC, jaixchaudhary commented on index.js
> +// import LMChatClient from '@likeminds.community/chat-js';
remove unnecessary comments

2023-08-17 12:50 UTC, ishaan1607 requested changes

2023-08-17 14:43 UTC, arnavr15 commented on ChatSX/components/Poll/CreatePollScreen/index.tsx
> +      let payload1 = {
changed to `getConversationPayload`

2023-08-28 11:19 UTC, ishaan1607 approved these changes

2023-08-28 11:41 UTC, merged