[LM-9366] Scroll Listener
NateshR/LikeMinds-ReactNative-Chat-SX pull request #155
Opened 2023-08-21 07:08 UTC by arnavr15

## Description

**Features**
- Added dual side scroll listener

**Bugs**

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Hotfix (fixes a breaking changes)
- [x] New Feature (non-breaking change which adds functionality)
- [ ] Other, please describe:

### Author Checklist

- [x] Assignee added
- [x] Reviewer added
- [x] Description added
- [ ] Unit test cases added

### Reviewer Checklist

- [ ] PR title starts with Jira ticket number prefix
- [ ] If hotfix, Add Hotfix as prefix in PR title
- [ ] Label added
- [ ] Commit messages follows standard format (added, changed, removed, code commented and chore)
- [ ] Description about the Feature/ Bugs added

2023-08-23 11:29 UTC, ishaan1607 requested changes

2023-08-23 11:29 UTC, ishaan1607 commented on ChatSX/screens/ChatRoom/index.tsx
> +      paginateBy: 10,
reset it to 50

2023-08-23 11:29 UTC, ishaan1607 commented on ChatSX/screens/ChatRoom/index.tsx
> +      paginateBy: 10,
reset it to 50

2023-08-23 11:29 UTC, ishaan1607 commented on ChatSX/screens/ChatRoom/index.tsx
> +  const scrollToVisibleIndex = (ind: number) => {
rename to `index`

2023-08-23 11:29 UTC, ishaan1607 commented on ChatSX/screens/ChatRoom/index.tsx
>      if (res.conversations.length == 0) {
add option chaining

2023-08-23 11:29 UTC, ishaan1607 commented on ChatSX/screens/ChatRoom/index.tsx
> +      const len = res.conversations.length;
add option chaining

2023-08-23 11:29 UTC, ishaan1607 commented on ChatSX/screens/ChatRoom/index.tsx
> +        estimatedItemSize={30}
Why 30?

2023-08-25 07:00 UTC, arnavr15 commented on ChatSX/screens/ChatRoom/index.tsx
> +        estimatedItemSize={30}
will make it 50

2023-09-08 05:21 UTC, ishaan1607 requested changes

2023-09-08 05:21 UTC, ishaan1607 commented on ChatSX/screens/ChatRoom/index.tsx
> +  useEffect(() => {
add comments what is use of this `useEffect()`

2023-09-08 08:14 UTC, ishaan1607 approved these changes

2023-09-12 13:08 UTC, merged