[LM-9897] Peer Testing Bugs
NateshR/LikeMinds-ReactNative-Chat-SX pull request #167
Opened 2023-10-11 18:13 UTC by arnavr15

## Description

**Features**

**Bugs**

**What kind of change does this PR introduce?** (check at least one)

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Hotfix (fixes a breaking changes)
- [ ] New Feature (non-breaking change which adds functionality)
- [ ] Other, please describe:

### Author Checklist

- [x] Assignee added
- [x] Reviewer added
- [x] Description added
- [ ] Unit test cases added

### Reviewer Checklist

- [ ] PR title starts with Jira ticket number prefix
- [ ] If hotfix, Add Hotfix as prefix in PR title
- [ ] Label added
- [ ] Commit messages follows standard format (added, changed, removed, code commented and chore)
- [ ] Description about the Feature/ Bugs added

2023-10-12 06:13 UTC, ishaan1607 requested changes

2023-10-12 06:13 UTC, ishaan1607 commented on ChatSX/components/AttachmentConversations/index.tsx
> +  if (attachment0) {
rename `attachment0` to `firstAttachment`

2023-10-12 06:13 UTC, ishaan1607 commented on ChatSX/components/HomeFeedItem/index.tsx
> +      } else if (attachments[i].type == 'pdf') {
create enums for 'pdf', 'video' etc

2023-10-12 06:13 UTC, ishaan1607 commented on ChatSX/components/InputBox/index.tsx
>            body: {chatRequestState: 1},
replace `1` to enums created

2023-10-12 06:13 UTC, ishaan1607 commented on ChatSX/constants/Styles.ts
> +    PREMEDIUM: 13,
rename to regular

2023-10-12 06:51 UTC, ishaan1607 approved these changes

2023-10-13 00:40 UTC, jaixchaudhary approved these changes

2023-10-13 00:41 UTC, merged