[LM-10094] GIF Support
NateshR/LikeMinds-ReactNative-Chat-SX pull request #190
Opened 2023-11-23 04:51 UTC by jaixchaudhary

## Description

**Features**
-- GIF Support

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Hotfix (fixes a breaking changes)
- [ ] New Feature (non-breaking change which adds functionality)
- [ ] Other, please describe:

### Author Checklist

- [ ] Assignee added
- [ ] Reviewer added
- [ ] Description added
- [ ] Unit test cases added

### Reviewer Checklist

- [ ] PR title starts with Jira ticket number prefix
- [ ] If hotfix, Add Hotfix as prefix in PR title
- [ ] Label added
- [ ] Commit messages follows standard format (added, changed, removed, code commented and chore)
- [ ] Description about the Feature/ Bugs added

2023-11-29 10:19 UTC, ishaan1607 requested changes

2023-11-29 10:19 UTC, ishaan1607 commented on ChatSX/components/InputBox/index.tsx
> +                !(chatRequestState === 0 || chatRequestState === null) &&
instead of `0` or `null` use enums already created

2023-11-29 10:19 UTC, ishaan1607 commented on android/app/build.gradle
> +    implementation 'com.facebook.fresco:webpsupport:2.5.0'
why do we need this?

2023-12-01 07:56 UTC, ishaan1607 approved these changes

2023-12-05 10:10 UTC, ishaan1607 approved these changes

2023-12-05 10:14 UTC, jaixchaudhary commented on android/app/build.gradle
> +    implementation 'com.facebook.fresco:webpsupport:2.5.0'
For gif support in android

2023-12-05 10:14 UTC, merged